version: '3.4'

services:
  hishare:
    image: ${DOCKER_REGISTRY-}hishare
    build:
      context: .
      dockerfile: HiShare/Dockerfile
    environment:
      - Db_ConnectionString
    depends_on:
      - mongo
    ports:
      - "5000:80"
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root