version: '3.4'

services:
  hishare:
    image: jimchen8889/hishare:latest
    build:
      context: .
      dockerfile: HiShare/Dockerfile
    environment:
      - Db_ConnectionString
      - REACT_APP_API_URL
      - REACT_APP_RECAPTCHA_SITEKEY
      - Recaptcha_SecretKey
    depends_on:
      - mongo
    ports:
      - "5555:80"
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: ./data
        target: /data/db
